### ISSUE TITLE
Cant get it to work

### ISSUE THREAD

**Issue by pjator** [g-kiss/Home-Assistant-custom-shutter-icons#1]
Sorry but I cant get this to work. I added it in the lovelace "resources" but no icon shows up. 

Any suggestions to what I might be doing wrong? Is there a place where I should store the SVG files? I have understood the instructions that the SVG files are not needed or am I wrong here?

**Comment by g-kiss** [comment]
You need only custom-shutter-icons.js file, SVG files not neded . You have to refer like this: 'custom-shutter:shutter-1'

**Comment by pjator** [comment]
Relay strange, that was exactly how I did it but i did not get it to work.

But now I changed the folder location from www to a sub folder /www/icons/ and after that I got it to work. Dont think it was related but maybe I did something else wrong. Sorry for disturbing and thanks for the help.
